language: ruby
rvm:
  - 2.1.5
  - 2.2.2
gemfile:
  - Gemfile
  - Gemfile.next
matrix:
  exclude:
    - rvm: 2.1.5
      gemfile: Gemfile.next
    - rvm: 2.2.2
      gemfile: Gemfile
bundler_args: --without production
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:drop db:create db:migrate db:seed
script: bundle exec rspec spec
